### ISSUE TITLE
SWMFAC Old Inspection By County - Issues

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#27]
1. The report view is not user friendly, records are broken into several pages making it tedious, e.g Anne arundel has 74 pages. can reduce the row spacing?

2. The report is not returning all the records that fall within a selected county. I tried to investigate if those records don't have inspections associated but encountered issues with the system loading those records on the results screen. Replicate with 010508 -10,

**Comment by TaraF** [comment]
@ladejobi -- 1 is fixed, for 2, the example you gave does not have an inspection associated to it.  I revisited my logic, and don't see any problems with it.  Can you find another example where there is an inspection but it doesn't show up in the report?

**Comment by ladejobi** [comment]
@TaraF both issues are still persisting. Here is a screenshot of issue 1 below. 

![image](https://user-images.githubusercontent.com/8458252/33277887-e15d7d56-d367-11e7-9295-d3b9ffeeb129.png)

**Comment by TaraF** [comment]
@ladejobi -- didn't stakeholders request to drop this report for now? if so, can you assign to Mohsin to drop from UI?

**Comment by ladejobi** [comment]
@TaraF you're correct. @mohsinkar remove SWMFAC Old Inspections By County report from UI

**Comment by ladejobi** [comment]
Fix validated
