### ISSUE TITLE
Maint Tab - Add Workflow - Error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#40]
The add workflow does not work as expected.
1. It does not successfully commit/display newly added record on the UI
2. System does not show highlight the newly added record (in red)
3. The system does not populate the "Created Date" field after user completes the add workflow

**Comment by mohsinkar** [comment]
@ladejobi 
1 and 3 are fixed. Not sure what you mean by (in red) can you give me an example if is currently working like the rating Add.

**Comment by ladejobi** [comment]
No. 1 is fixed. New issues
1.During the add workflow the system generates date fields that are not valid
2.The system does not persist date fields on the UI after user commits it to the database 
3. The system displays an erroneous value for the time stamp on the Created Date field.always shpwing 12:00:00AM

**Comment by ladejobi** [comment]
These issues still persist -
Maint Tab and Insp/Rat Tab -  System does not commit all date fields after user completes the add and edit workflow on both tabs.

**Comment by ladejobi** [comment]
The Insp/Rat tab date issue has been fixed.These issue persist:
1. The system now persist all fields upon user completing the add workflow however the system does not display the newly added record as the latest
2. The date issue is still been encountered when user executes the edit maint record workflow. System does not commit changes.
3.The system displays an erroneous value for the time stamp on the Created Date field.always showing 12:00:00AM

**Comment by ladejobi** [comment]
Only 3 is fixed. 1 and 2 are still are issue. 
For 2, system now commits changes but displays erroneous date values. The system also erroneously change other date fields after user edit a date field.

**Comment by ladejobi** [comment]
1 has been fixed. 2 is partially fixed. The system now persist the changes however it's changing other date fields on the fly once user commits any maint field edit.

**Comment by ladejobi** [comment]
Bug fix been tracked in Bug #62.
